services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  
    container_name: pawswipe_backend
    ports:
      - "5001:5001"
    environment:
      MONGODB_URI: "."
      PORT: "."
      JWT_SECRET: "."
      CLOUDINARY_CLOUD_NAME: "."
      COULDINARY_API_KEY: "."
      CLOUDINARY_API_SECRET: "."
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pawswipe_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

